MonsieurBiz\SyliusCmsPagePlugin\Entity\PageTranslation:
    properties:
        title:
            -   NotBlank:
                    groups: [monsieurbiz]
            -   Length:
                    min: 2
                    max: 255
                    groups: [monsieurbiz]
        slug:
            -   NotBlank:
                    groups: [monsieurbiz]
            -   Length:
                    min: 2
                    max: 255
                    groups: [monsieurbiz]
        content:
            -   NotBlank:
                    groups: [monsieurbiz]
